# Generated by Django 5.0.3 on 2024-03-17 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchPercentage', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='employee.employee')),
                ('jobPosting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='employer.jobposting')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField()),
                ('applicationStatus', models.CharField(choices=[('WAIT_FOR_INTERVIEW', 'waiting for the interview'), ('ACCEPTED_FOR_INTERVIEW', 'accepted for interview'), ('REFUSED', 'refused'), ('ACCEPTED_AFTER_INTERVIEW', 'accepted after interview'), ('GOT_THE_JOB', 'got the job'), ('HOLD', 'hold'), ('REFUSE_AFTER_INTERVIEW', 'refuse after interview'), ('JOB_TAKEN', 'job taken')], max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='employee.employee')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='employer.jobposting')),
            ],
        ),
    ]
