# Generated by Django 5.0.3 on 2024-04-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobMatch', '0003_alter_analytics_matchpercentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='matchPercentage',
            field=models.FloatField(null=True),
        ),
    ]
