# Generated by Django 5.0.3 on 2024-03-08 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobMatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
