# Generated by Django 5.0.3 on 2024-04-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='jobStatus',
            field=models.CharField(choices=[('POSTED', 'Posted'), ('INTERVIEW', 'Interview'), ('HOLD', 'Hold'), ('DONE', 'Done'), ('CANCELED', 'Canceled')], max_length=255),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='salaryMax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='salaryMin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
