# Generated by Django 5.0.3 on 2024-04-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_alter_jobposting_jobstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='numberOfApplicants',
            field=models.IntegerField(default=0),
        ),
    ]
