# Generated by Django 5.0.3 on 2024-04-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_jobposting_numberofapplicants'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='salary',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
