# Generated by Django 5.0.3 on 2024-04-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_jobposting_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='level',
            field=models.CharField(choices=[('ENTRY', 'Entry'), ('INTERMEDIATE', 'Intermediate'), ('SENIOR', 'Senior'), ('EXPERT', 'Expert')], default='ENTRY', max_length=255),
        ),
    ]
