# Generated by Django 5.0.3 on 2024-05-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_alter_jobposting_jobstatus_alter_jobposting_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='companyName',
            field=models.CharField(default='companyName', max_length=255),
        ),
    ]
