# Generated by Django 5.0.3 on 2024-05-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0008_jobposting_companyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='companyName',
            field=models.CharField(max_length=255),
        ),
    ]
